### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by kastnerp** [eddes/buildingphysics#15]
Hi Edouard,

I wanted to take a look at [this example](https://github.com/eddes/buildingphysics/blob/master/chapter_2/4_geothermal_heat_pump/geothermal_HP.py) but it seems to be dependent on "Ta_out.npy", which seems to be an ambient temperature time series that is not part of the repository. One can make one up for the time being but I just wanted to let you know.
Great job and congrats on this effort otherwise!

Best,

Patrick

**Comment by YannSc** [comment]
Hi Patrick,

Thank you for this feedback. I will check if I can add the original or a sample dataset to fix this issue. 

Best,
Yann

**Comment by eddes** [comment]
Hi Patrick,

Thank you for your accurate feedback and acknowledgement, I have added the missing file in the repository.
Don't hesitate if you notice other inconsistencies that may have survived our trials of eradication ;-)

See you around!
Regards,
Edouard
