### ISSUE TITLE
Pre release

### ISSUE THREAD

**Issue by YannSc** [eddes/buildingphysics#9]
Étapes à planifier pour la release
- changement de la section "about" du projet avec lien vers la page du livre
- mise en ligne de la page du livre
- test et intégration des commits complémentaires
- préparer note de communication

**Comment by eddes** [comment]
Côté livre : 
    - mise à jour des liens vers notebookz et github
    - vérif nomenclature
    - suite et fin heat&mass transfer
    - vérif facilité de modif en cas d'hébergement sur researchgate
merci YannSc, c'est pour bientôt ! ;-)
